version: 2.1
orbs:
  node: circleci/node@5.1.0
jobs:
  lint:
    docker:
      - image: cimg/node:18.4
    steps:
      - checkout
      - restore_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: v1-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: lint
          command: npm run lint
workflows:
  default:
    jobs:
      - lint
